# Give the project a nice name
spring.application.name: backend

# Set the port
server.port: ${SERVER_PORT:8081}

# Enable and configure the credentials for actuator
spring.security.user:
  name: ${USER}
  password: ${PASSWORD}
  roles: ACTUATOR

# Enable all the actuator endpoints for HTTP (keep them under the base path) and JMX
management.endpoints:
  web:
    base-path: /
    exposure.include: "*"
  jmx.exposure.include: "*"
