- hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: no


  vars_files:
    - variables.yml


  vars:
      kibana_basic_auth: "{{ elasticsearch_user }}:{{ elasticsearch_password  }}"


  pre_tasks:
    - name: Install Python2 to make Ansible work
      raw: sudo apt-get update && sudo apt-get -y install python-minimal


  tasks:


    # System
    - name: Update and upgrade apt packages
      apt: upgrade=dist

    - name: Install NTP to avoid time drift
      apt: name={{ item }} state=latest
      with_items:
        - ntp
        - ntpdate

    - name: Install the JRE
      apt: name=openjdk-8-jre-headless state=latest install_recommends=no


    # Global Elasticsearch configuration
    - name: Register a global index template
      command: >
        curl -XPUT "{{ elasticsearch_host }}/_template/template_global"
             -u "{{ elasticsearch_user }}:{{ elasticsearch_password }}"
             -H "Content-Type: application/json"
             -d '{"template": "*", "settings": {"number_of_shards": 1}}'
      run_once: true


    # Filebeat
    - name: Install Filebeat
      apt: deb={{ elastic_download }}/downloads/beats/filebeat/filebeat-{{ elastic_version }}-amd64.deb

    - name: Change the Filebeat configuration
      template: src=templates/filebeat.yml dest=/etc/filebeat/filebeat.yml

    - name: Restart Filebeat and make sure it autostarts
      service: name=filebeat state=restarted enabled=yes

    - name: Add a default index pattern using Filebeat and hide the X-Pack banner
      command: >
        curl -XPUT "{{ elasticsearch_host }}/.kibana/doc/config:{{ elastic_version }}"
             -u "{{ elasticsearch_user }}:{{ elasticsearch_password }}"
             -H "Content-Type: application/json"
             -d '{"defaultIndex": "filebeat-*", "xPackMonitoring:showBanner": false}'
      run_once: true


    # Metricbeat
    - name: Install Metricbeat
      apt: deb={{ elastic_download }}/downloads/beats/metricbeat/metricbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Metricbeat configuration
      template: src=templates/metricbeat.yml dest=/etc/metricbeat/metricbeat.yml

    - name: Restart Metricbeat and make sure it autostarts
      service: name=metricbeat state=restarted enabled=yes


    # Packetbeat
    - name: Install Packetbeat
      apt: deb={{ elastic_download }}/downloads/beats/packetbeat/packetbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Packetbeat configuration
      template: src=templates/packetbeat.yml dest=/etc/packetbeat/packetbeat.yml

    - name: Restart Packetbeat and make sure it autostarts
      service: name=packetbeat state=restarted enabled=yes



    # nginx
    - name: Install nginx
      apt: name=nginx state=latest

    - name: Add the certbot repository
      apt_repository: repo='ppa:certbot/certbot'

    - name: Install certbot and update the cache for the new PPA
      apt: name=python-certbot-nginx state=latest update_cache=yes

    - name: Add the hostname to the certificates to create
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"

    - name: Add more domains to the frontend certificate
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"
          - "{{ domain }}"
          - "www.{{ domain }}"
      when: inventory_hostname == "frontend." + domain

    - name: Add more domains to the monitor certificate
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"
          - "kibana.{{ domain }}"
      when: inventory_hostname == "monitor." + domain

    - name: Create the certificate
      command: >
        certbot certonly --standalone --agree-tos --email admin@{{ domain }} -d {{ certificates | join(',') }}
        creates=/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem

    - name: Add crontab to renew certificates every second month on Sunday night
      cron: minute="30" hour="3" weekday="0" month="*/2" job="certbot renew >> /var/log//var/log/letsencrypt/renew.log"

    - name: Generate strong dhparams, but only if the file doesn't exist
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096 creates=/etc/ssl/certs/dhparam.pem

    - name: Set a global TLS configuration
      template: src=templates/tls.conf dest=/etc/nginx/tls.conf

    - name: Change the nginx configuration
      template: src=templates/nginx.conf dest=/etc/nginx/sites-available/default

    - name: Reload nginx and make sure it autostarts
      service: name=nginx state=reloaded enabled=yes

    - name: Try HTTP
      uri: url="http://{{ inventory_hostname }}" follow_redirects=none status_code=301
      register: response
      retries: 3
      delay: 2

    - name: Fail if HTTP is not being redirected to HTTPS
      fail:
      when: response.status != 301

    - name: Check HTTPS
      openssl_certificate:
        path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
        provider: assertonly
        issuer:
          O: Let's Encrypt
        has_expired: false
        subject_alt_name:
          - "DNS:{{ inventory_hostname }}"

    - name: Check HTTPS apex
      openssl_certificate:
        path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
        provider: assertonly
        issuer:
          O: Let's Encrypt
        has_expired: false
        subject_alt_name:
          - "DNS:{{ domain }}"
      when: inventory_hostname == "frontend." + domain
