- hosts: monitor
  remote_user: ubuntu
  become: true
  gather_facts: no


  vars_files:
    - variables.yml


  tasks:


    # Heartbeat
    - name: Install Heartbeat
      apt: deb={{ elastic_download }}/downloads/beats/heartbeat/heartbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Heartbeat configuration
      template: src=templates/heartbeat.yml dest=/etc/heartbeat/heartbeat.yml

    - name: Restart Heartbeat and make sure it autostarts
      service: name=heartbeat-elastic state=restarted enabled=yes


    # Watcher
    - name: Add an example Watch from a local file
      command: >
        curl -XPUT "{{ elasticsearch_host }}/_xpack/watcher/watch/down"
             -u "{{ elasticsearch_user }}:{{ elasticsearch_password }}"
             -H "Content-Type: application/json"
             -d "@files/watch-down.json"
      delegate_to: 127.0.0.1
      become: false
