- hosts: monitor
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  post_tasks:
    - name: Get the local user
      command: whoami
      register: local_username
      delegate_to: 127.0.0.1
      become: false
    - name: Store the playbook run event in Elasticsearch so it can be used as an annotation
      uri:
        url: "{{elasticsearch_host}}events/deployment"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        body:
          "@timestamp": "{{ ansible_date_time.iso8601 }}"
          application: configure_monitor
          system: ansible
          host: "{{ inventory_hostname }}"
          user: "{{ local_username.stdout }}"
        status_code: 201


  tasks:


    # Heartbeat
    - name: Install Heartbeat
      apt: deb={{ elastic_download }}/downloads/beats/heartbeat/heartbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Heartbeat configuration
      template: src=templates/heartbeat.yml dest=/etc/heartbeat/heartbeat.yml

    - name: Restart Heartbeat and make sure it autostarts
      service: name=heartbeat-elastic state=restarted enabled=yes


    # Dashboard user
    - name: Create a role for a user to only view the dashboards
      uri:
        url: "{{elasticsearch_host}}.security-6/doc/role-read_dashboard"
        body_format: json
        method: PUT
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        body: "{{ lookup('file','security_role_dashboard.json') }}"
        status_code:
          - 201
          - 200

    - name: Create the dashboard user with the credentials admin password
      uri:
        url: "{{elasticsearch_host}}.security-6/doc/user-admin"
        body_format: json
        method: PUT
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        body: "{{ lookup('file','security_user_dashboard.json') }}"
        status_code:
          - 201
          - 200


    # Watcher
    - name: Add an example Watch from a local file
      uri:
        url: "{{elasticsearch_host}}_xpack/watcher/watch/heapsize"
        body_format: json
        method: PUT
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        body: "{{ lookup('file','alerting_heapsize.json') }}"
        status_code:
          - 201
          - 200
