- hosts: monitor
  remote_user: ubuntu
  become: true
  gather_facts: no


  vars_files:
    - variables.yml


  tasks:


    # Heartbeat
    - name: Purge Heartbeat since it might collide with the Linux package
      apt: name=heartbeat state=absent purge=yes

    - name: Install Heartbeat
      apt: deb={{ elastic_download }}/downloads/beats/heartbeat/heartbeat-{{ elastic_version }}-amd64.deb

    - name: Change the Heartbeat configuration
      template: src=templates/heartbeat.yml dest=/etc/heartbeat/heartbeat.yml

    - name: Restart Heartbeat and make sure it autostarts, but stop it for now
      service: name=heartbeat state=stopped enabled=yes

    - name: Add Heartbeat dashboard
      command: /usr/share/heartbeat/scripts/import_dashboards -es {{ elasticsearch_host }} -user {{ elasticsearch_user }} -pass {{ elasticsearch_password }}


    # Httpbeat
    - name: Install Httpbeat
      apt: deb=https://github.com/christiangalsterer/httpbeat/releases/download/4.0.0/httpbeat-4.0.0-amd64.deb

    - name: Change the Httpbeat configuration
      template: src=templates/httpbeat.yml dest=/etc/httpbeat/httpbeat.yml

    - name: Restart Httpbeat and make sure it autostarts, but stop it for now
      service: name=httpbeat state=stopped enabled=yes

    - name: Get the Httpbeat index pattern for Kibana
      get_url:
        url: https://raw.githubusercontent.com/christiangalsterer/httpbeat/master/_meta/kibana/index-pattern/httpbeat.json
        dest: /opt/httpbeat.json

    - name: Add Httpbeat index pattern to Kibana (there is no dashboard to do that)
      command: >
        curl -XPUT "{{ elasticsearch_host }}/.kibana/index-pattern/httpbeat-*"
             -u "{{ elasticsearch_user }}:{{ elasticsearch_password }}"
             -H "Content-Type: application/json"
             -d "@/opt/httpbeat.json"

    - name: Clean up and remove the index pattern file again
      file:
        path: /opt/httpbeat.json
        state: absent

      command: >
             -u "{{ elasticsearch_user }}:{{ elasticsearch_password }}"
             -H "Content-Type: application/json"
