- hosts: frontend
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  tasks:

    - name: Package the JAR
      local_action: shell cd ../java/bad/; gradle build
      become: false

    - name: Deploy our bad.jar
      copy:
        src: ../java/bad/build/libs/Bad-1.0.jar
        dest: /opt/bad.jar
        owner: ubuntu
        group: ubuntu
        mode: 0500

    - name: Get the local user
      command: whoami
      register: local_username
      delegate_to: 127.0.0.1
      become: false

    - name: Store the deployment event in Elasticsearch so it can be used as an annotation
      uri:
        url: "{{elasticsearch_host}}events/deployment"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        body:
          "@timestamp": "{{ ansible_date_time.iso8601 }}"
          application: bad
          system: java
          host: "{{ inventory_hostname }}"
          user: "{{ local_username.stdout }}"
        status_code: 201
