- hosts: monitor
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  tasks:

    - include: include_deploy_boot.yml
      vars:
        application: zipkin

    - name: Restart Zipkin to apply the parameters that were just set
      systemd: name="zipkin" state=restarted daemon_reload=yes
