- hosts: monitor
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  tasks:

    - include: include_deploy_boot.yml
      vars:
        application: zipkin
