- hosts: monitor
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  post_tasks:
    - include_tasks: include_event.yml
      vars:
        application: deploy_zipkin


  tasks:

    - include_tasks: include_deploy_boot.yml
      vars:
        application: zipkin
