- hosts: frontend
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  tasks:

    - name: Deploy our bad.jar
      copy:
        src: ../java/bad/build/libs/Bad-1.0.jar
        dest: /opt/bad.jar
        owner: ubuntu
        group: ubuntu
        mode: 0500

    - name: Store the deployment event in Elasticsearch so it can be used as an annotation
      command: >
        curl -XPOST "{{ elasticsearch_host }}/events/deployment"
             -u "{{ elasticsearch_user }}:{{ elasticsearch_password }}"
             -H "Content-Type: application/json"
             -d '{"@timestamp": "{{ ansible_date_time.iso8601 }}", "application": "bad", "host": "{{ inventory_hostname }}"}'

