apm-server:
  host: "0.0.0.0:8200"

  secret_token: "{{ apm_secret }}"


setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"


setup:
  kibana:
    host: "{{ kibana_host }}"
    username: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_password }}"
  dashboards.enabled: true
