filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/apps/*.json
  document_type: java-app
  json.message_key: log


filebeat.modules:
- module: system
- module: nginx


name: "{{ inventory_hostname }}"


processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"
