heartbeat.monitors:
- type: http
  urls: ["https://{{ domain }}/health"]
  schedule: '@every 10s'
  timeout: 3s
  check.response.status: 200


name: "{{ inventory_hostname }}"


processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"
