heartbeat.monitors:
- type: http
  urls: ["http://{{ domain }}/good"]
  schedule: '@every 10s'
  timeout: 3s
  check.response.status: 200


processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"
