packetbeat.interfaces.device: any


packetbeat.flows:
  timeout: 30s
  period: 10s


packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true


packetbeat.protocols.http:
  ports: [80, 8080]
  real_ip_header: "X-Forwarded-For"


name: "{{ inventory_hostname }}"


processors:

- add_cloud_metadata: ~

- drop_event:
    when:
      or:
        # Exclude traces from Zipkin
        - contains.path: "/api/v"
        # Exclude pinging metrics
        - equals.path: "/metrics"
        # Exclude pinging health
        - equals.path: "/health"


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"
