packetbeat.interfaces.device: any


packetbeat.flows:
  timeout: 30s
  period: 10s


packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true


packetbeat.protocols.http:
  ports: [80]


name: "{{ inventory_hostname }}"


processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"
