packetbeat.interfaces.device: any


packetbeat.protocols.http:
  ports: [80]
  send_request: true
  send_response: true


processors:
- add_cloud_metadata:
    timeout: 3s


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"
